# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Madiha Z Sadiq
description: 
baseurl: ""
url: "https://madihazs.github.io"
og_image: /assets/img/me.png
google_analytics: ""

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: CV

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: madihaz.sadiq@eui.eu
  follow:
    - type: twitter
      name: Twitter
      link: http://twitter.com/sadiq_madiha
      username: "@sadiq_madiha"
    - type: bluesky
      name: Bluesky
      link: http://bsky.app/profile/madihazs.bsky.social
    - type: linkedin
      name: LinkedIn
      link: http://www.linkedin.com/in/madiha-z-sadiq-136a15178/
    - type: github
      name: GitHub
      link: http://github.com/madihazs

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
